# -*- coding: utf-8 -*-
"""Challenge Alura Store

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CtHXh4cDUn3qRrfU5_upoBH96NUz53Ls

### Importación de datos
"""

import pandas as pd
import matplotlib.pyplot as plt


url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

"""#1. Análisis de facturación


"""

tienda_income = tienda['Precio'].sum()
tienda2_income = tienda2['Precio'].sum()
tienda3_income = tienda3['Precio'].sum()
tienda4_income = tienda4['Precio'].sum()

print(tienda_income)
print(tienda2_income)
print(tienda3_income)
print(tienda4_income)

total_facturacion = tienda_income + tienda2_income + tienda3_income + tienda4_income
print(total_facturacion)

tiendas = ['tienda1', 'tienda2', 'tienda3', 'tienda4']
income = [tienda_income, tienda2_income, tienda3_income, tienda4_income]
plt.bar(tiendas, income)
plt.xlabel('Tiendas')
plt.ylabel('Income')
plt.title('Ingreso por tienda')

"""# 2. Ventas por categoría"""

categoria_grouped = tienda.groupby('Categoría del Producto')['Precio'].sum()
print(categoria_grouped)

plt.pie(categoria_grouped, labels=categoria_grouped.index, autopct="%1.1f%%")
plt.title('Distribución por categoría de producto')
plt.show()

categoria1_grouped = tienda2.groupby('Categoría del Producto')['Precio'].sum()
print(categoria1_grouped)

plt.pie(categoria1_grouped, labels=categoria1_grouped.index, autopct="%1.1f%%")
plt.title('Distribución por categoría de producto')
plt.show()

categoria2_grouped = tienda3.groupby('Categoría del Producto')['Precio'].sum()
print(categoria2_grouped)

plt.pie(categoria2_grouped, labels=categoria2_grouped.index, autopct="%1.1f%%")
plt.title('Distribución por categoría de producto')
plt.show()

categoria3_grouped = tienda4.groupby('Categoría del Producto')['Precio'].sum()
print(categoria3_grouped)

plt.pie(categoria3_grouped, labels=categoria3_grouped.index, autopct="%1.1f%%")
plt.title('Distribución por categoría de producto')
plt.show()

"""# 3. Calificación promedio de la tienda

"""

promedio_calificaciones = tienda.groupby('Lugar de Compra')['Calificación'].mean()
print(promedio_calificaciones)

plt.plot(promedio_calificaciones.index, promedio_calificaciones.values, marker= "o")
plt.xlabel('Lugar de Compra')
plt.ylabel('Calificación Promedio')
plt.title('Calificación Promedio por Lugar de Compra')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

promedio_calificaciones2 = tienda2.groupby('Lugar de Compra')['Calificación'].mean()
print(promedio_calificaciones2)

plt.plot(promedio_calificaciones2.index, promedio_calificaciones2.values, marker= "o")
plt.xlabel('Lugar de Compra')
plt.ylabel('Calificación Promedio')
plt.title('Calificación Promedio por Lugar de Compra')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

promedio_calificaciones3 = tienda3.groupby('Lugar de Compra')['Calificación'].mean()
print(promedio_calificaciones3)

plt.plot(promedio_calificaciones3.index, promedio_calificaciones3.values, marker= "o")
plt.xlabel('Lugar de Compra')
plt.ylabel('Calificación Promedio')
plt.title('Calificación Promedio por Lugar de Compra')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

promedio_calificaciones4 = tienda4.groupby('Lugar de Compra')['Calificación'].mean()
print(promedio_calificaciones4)

plt.plot(promedio_calificaciones4.index, promedio_calificaciones4.values, marker= "o")
plt.xlabel('Lugar de Compra')
plt.ylabel('Calificación Promedio')
plt.title('Calificación Promedio por Lugar de Compra')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""# 4. Productos más y menos vendidos"""

todas_tiendas = pd.concat([tienda, tienda2, tienda3, tienda4])
grouped = todas_tiendas.groupby(['Lugar de Compra', 'Categoría del Producto'])['Cantidad de cuotas'].sum()

def top_and_bottom(store_data, n=5):
    top = store_data.nlargest(n)
    bottom = store_data.nsmallest(n)
    return pd.concat([top, bottom])

top_bottom_products = grouped.groupby('Lugar de Compra').apply(top_and_bottom)





"""# 5. Envío promedio por tienda"""

todas_tiendas = pd.concat([tienda, tienda2, tienda3, tienda4])
costo_promedio_envío = todas_tiendas.groupby('Lugar de Compra')['Costo de envío'].mean()
print(costo_promedio_envío)

tienda_envío = tienda.groupby('Lugar de Compra')['Costo de envío'].mean()
print(tienda_envío)

plt.figure(figsize=(10, 6))
plt.bar(tienda_envío.index, tienda_envío.values, width=0.5)
plt.xlabel('Tienda')
plt.ylabel('Costo de envío promedio')
plt.title('Costo de envío promedio por tienda')
plt.xticks(rotation=45, ha='right')
plt.show()

tienda3_envío = tienda3.groupby('Lugar de Compra')['Costo de envío'].mean()
print(tienda3_envío)

tienda4_envío = tienda4.groupby('Lugar de Compra')['Costo de envío'].mean()
print(tienda4_envío)

plt.figure(figsize=(10, 6))
plt.bar(tienda3_envío.index, tienda3_envío.values, width=0.5)
plt.xlabel('Tienda')
plt.ylabel('Costo de envío promedio')
plt.title('Costo de envío promedio por tienda')
plt.xticks(rotation=45, ha='right')
plt.show()

plt.figure(figsize=(10, 6))
plt.bar(tienda4_envío.index, tienda4_envío.values, width=0.5)
plt.xlabel('Tienda')
plt.ylabel('Costo de envío promedio')
plt.title('Costo de envío promedio por tienda')
plt.xticks(rotation=45, ha='right')
plt.show()

plt.figure(figsize=(10, 6))
plt.bar(costo_promedio_envío.index, costo_promedio_envío.values, width=0.5)
plt.xlabel('Tienda')
plt.ylabel('Costo de envío promedio')
plt.title('Costo de envío promedio por tienda')
plt.xticks(rotation=45, ha='right')
plt.show()

"""Informe Final:
Introducción

En un entorno empresarial cada vez más competitivo, la toma de decisiones
estratégicas debe estar respaldada por información objetiva y análisis rigurosos.
En este contexto, se ha llevado a cabo un análisis de datos detallado sobre el desempeño de cuatro tiendas pertenecientes a una misma organización.
El propósito principal de este estudio es identificar, con base en métricas clave como ventas, costos operativos, rentabilidad, calificación y otros indicadores relevantes,
cuál de estas tiendas presenta el menor desempeño y, por tanto, debería considerarse para su venta. Esta decisión no solo busca optimizar los recursos de la empresa,
sino también fortalecer su estructura financiera y operativa, enfocando esfuerzos en las unidades más rentables y con mayor potencial de crecimiento.

Análisis comparativo del desempeño de cuatro tiendas con fines estratégicos de desinversión

En el marco de una revisión integral del rendimiento de las cuatro tiendas pertenecientes a la cadena, se realizó un análisis detallado de distintos indicadores clave
que permiten sustentar una eventual decisión de venta de una de las unidades. Este análisis incluyó variables como ingresos totales, distribución de ventas por categoría,
costos logísticos y calificaciones otorgadas por los clientes en distintas ciudades.

Ingresos y ventas por categoría

Uno de los primeros hallazgos relevantes fue la marcada diferencia en los ingresos generados por cada tienda. La tienda 4 se posiciona consistentemente como la de menor ingreso total.
A pesar de que, en términos generales, las ventas por categoría muestran un comportamiento relativamente homogéneo entre las cuatro tiendas, se detectó una caída considerable en la tienda 4
dentro de la categoría de electrodomésticos, donde solo representa el 27% de las ventas. Esta diferencia indica una debilidad significativa en una línea de producto que suele ser estratégica
para la rentabilidad general del negocio.

Costos logísticos y optimización de recursos

Con el fin de identificar posibles oportunidades de eficiencia, se construyó un gráfico de barras comparativo entre las tiendas 3 y 4 en relación con los costos de envío en distintas ciudades.
Si bien ambas tiendas presentan valores similares en este aspecto, la tienda 4 demuestra una leve mejor optimización de recursos en varias zonas geográficas. No obstante, esta diferencia, aunque
positiva, no es lo suficientemente significativa como para modificar la evaluación general de su rendimiento.

Satisfacción del cliente y reputación

Otro componente esencial del análisis fue la revisión de las calificaciones promedio otorgadas por los usuarios. Las tiendas 1 y 2 se destacan por tener una valoración positiva
en la mayoría de ciudades, manteniéndose en rangos superiores a 4 puntos, aunque con algunas excepciones puntuales donde se observaron valores por debajo de 3.
En contraste, las tiendas 3 y 4 presentan una tendencia general más baja, con promedios de calificación que oscilan entre 3 y 4, lo que refleja una menor percepción de calidad del
servicio o satisfacción general por parte de los clientes.

Conclusión y recomendaciones

Teniendo en cuenta el bajo nivel de ingresos, el bajo desempeño en categorías clave como electrodomésticos, y la valoración regular por parte de los clientes, se concluye que la tienda número 4
debería considerarse como la opción más viable para una eventual venta. Esta recomendación está sustentada en una visión integral del rendimiento, priorizando el promedio de ventas como factor
decisivo.

Sin embargo, para que esta acción tenga un impacto positivo en la eficiencia global de la cadena, se recomienda realizar una intervención específica en la tienda 3,
con el objetivo de reducir los costos logísticos, especialmente en ciudades como Manizales y Valledupar, donde actualmente se superan los $3.000 COP por envío.
Mantener estos costos por debajo de dicho umbral puede contribuir a una mejora sustancial en la rentabilidad de esta unidad."""